const iataMap = JSON.parse(
  '{"AAA": "French Polynesia/Tuamotu-Gambier", "AAE": "Algeria/Annaba", "AAL": "Denmark/Nordjylland", "AAM": "South Africa", "AAN": "United Arab Emirates/Abu Dhabi", "AAQ": "Russia/Krasnodarskiy Kray", "AAR": "Denmark/Midtjylland", "AAT": "China/Xinjiang", "AAX": "Brazil/Minas Gerais", "AAY": "Yemen/Hadramawt", "ABA": "Russian Federation/Khakasiya", "ABC": "Spain/Castilla-la Mancha", "ABD": "Iran/Khuzestan", "ABE": "United States/Pennsylvania", "ABI": "United States/Texas", "ABJ": "Ivory Coast/Abidjan", "ABK": "Ethiopia/Ogaden", "ABL": "United States/Alaska", "ABM": "Australia/Queensland", "ABQ": "United States/New Mexico", "ABR": "United States/South Dakota", "ABS": "Egypt/Aswan", "ABT": "Saudi Arabia/Al Baha", "ABV": "Nigeria/Abuja Capital Territory", "ABX": "Australia/New South Wales", "ABY": "United States/Georgia", "ABZ": "United Kingdom/Scotland", "ACA": "Mexico/Guerrero", "ACC": "Ghana/Greater Accra", "ACE": "Spain/Canary Islands", "ACH": "Switzerland/Canton of St. Gallen", "ACI": "United Kingdom/Channel Islands", "ACK": "United States/Massachusetts", "ACP": "Iran", "ACS": "Russia/Krasnoyarskiy Kray", "ACT": "United States/Texas", "ACV": "United States/California", "ACX": "China/Guizhou", "ACY": "United States/New Jersey", "ACZ": "Iran/Sistan va Baluchestan", "ADA": "Turkey/Adana", "ADB": "Turkey/\\u0130zmir", "ADD": "Ethiopia/Debub Shewa", "ADE": "Yemen/`Adan", "ADF": "Turkey/Ad\\u0131yaman", "ADJ": "Jordan/\'Amman", "ADK": "United States/Alaska", "ADL": "Australia/South Australia", "ADQ": "United States/Alaska", "ADU": "Iran/Ardabil", "ADX": "United Kingdom/Scotland", "ADZ": "Colombia/San Andres y Providencia", "AEH": "Chad/Ouaddai", "AEP": "Argentina/Ciudad de Buenos Aires", "AER": "Russia/Krasnodarskiy Kray", "AES": "Norway/More og Romsdal", "AET": "United States/Alaska", "AEX": "United States/Louisiana", "AEY": "Iceland/Akureyri", "AFA": "Argentina/Mendoza", "AFL": "Brazil/Mato Grosso", "AFS": "Uzbekistan/Nawoiy", "AFT": "Solomon Islands/Malaita", "AFZ":... (line truncated to 2000 chars)'
)

const countryCodeMap = JSON.parse(
  '{"AF":"Afghanistan","AX":"\u00c5land Islands","AL":"Albania","DZ":"Algeria","AS":"American Samoa","AD":"Andorra","AO":"Angola","AI":"Anguilla","AQ":"Antarctica","AG":"Antigua & Barbuda","AR":"Argentina","AM":"Armenia","AW":"Aruba","AU":"Australia","AT":"Austria","AZ":"Azerbaijan","BS":"Bahamas","BH":"Bahrain","BD":"Bangladesh","BB":"Barbados","BY":"Belarus","BE":"Belgium","BZ":"Belize","BJ":"Benin","BM":"Bermuda","BT":"Bhutan","BO":"Bolivia","BA":"Bosnia & Herzegovina","BW":"Botswana","BV":"Bouvet Island","BR":"Brazil","IO":"British Indian Ocean Territory","VG":"British Virgin Islands","BN":"Brunei","BG":"Bulgaria","BF":"Burkina Faso","BI":"Burundi","KH":"Cambodia","CM":"Cameroon","CA":"Canada","CV":"Cape Verde","BQ":"Caribbean Netherlands","KY":"Cayman Islands","CF":"Central African Republic","TD":"Chad","CL":"Chile","CN":"China","CX":"Christmas Island","CC":"Cocos (Keeling) Islands","CO":"Colombia","KM":"Comoros","CG":"Congo - Brazzaville","CD":"Congo - Kinshasa","CK":"Cook Islands","CR":"Costa Rica","CI":"C\u00f4te d\u2019Ivoire","HR":"Croatia","CU":"Cuba","CW":"Cura\u00e7ao","CY":"Cyprus","CZ":"Czechia","DK":"Denmark","DJ":"Djibouti","DM":"Dominica","DO":"Dominican Republic","EC":"Ecuador","EG":"Egypt","SV":"El Salvador","GQ":"Equatorial Guinea","ER":"Eritrea","EE":"Estonia","SZ":"Eswatini","ET":"Ethiopia","FK":"Falkland Islands","FO":"Faroe Islands","FJ":"Fiji","FI":"Finland","FR":"France","GF":"French Guiana","PF":"French Polynesia","TF":"French Southern Territories","GA":"Gabon","GM":"Gambia","GE":"Georgia","DE":"Germany","GH":"Ghana","GI":"Gibraltar","GR":"Greece","GL":"Greenland","GD":"Grenada","GP":"Guadeloupe","GU":"Guam","GT":"Guatemala","GG":"Guernsey","GN":"Guinea","GW":"Guinea-Bissau","GY":"Guyana","HT":"Haiti","HM":"Heard & McDonald Islands","HN":"Honduras","HK":"Hong Kong SAR China","HU":"Hungary","IS":"Iceland","IN":"India","ID":"Indonesia","IR":"Iran","IQ":"Iraq","IE":"Ireland","IM":"Isle of Man","IL":"Israel","IT":"Italy","JM":"Jamaica","JP":"... (line truncated to 2000 chars)'
)

function codeToCountry(code: string): string {
  if (code.includes('/')) {
    const parts = code.split('/')
    parts[0] = codeToCountry(parts[0])
    return parts.join('/')
  } else {
    return iataMap[code] || countryCodeMap[code] || code
  }
}

export { codeToCountry }
