name: Issue Translation

on:
  issue_comment:
    types: [created]
  issues:
    types: [opened]

jobs:
  translate:
    runs-on: ubuntu-latest
    steps:
      - uses: interactions-on-action/issue-translator@v1.1.0
